apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: training-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: quay.io/training/orders-service:v2.0.0
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: ORDER_PROCESS_TIMEOUT
              value: "30"
            - name: DB_USER
              value: "admin"
            - name: DB_PASS
              value: "admin123"
